### ISSUE TITLE
ANALYSIS.anasum.sh looks for script in wrong place

### ISSUE THREAD

**Issue by anne-duerr** [VERITAS-Observatory/Eventdisplay_AnalysisScripts_VTS#66]
Hi there,
I noticed that the ANALYSIS.anasum.sh script looks for the script `$(dirname "$0")/VTS/helper_scripts/UTILITY.readSubmissionCommand.sh` (on line 91) which does not exist in this repo. I think the correct line is `$(dirname "$0")/helper_scripts/UTILITY.readSubmissionCommand.sh`

**Comment by GernotMaier** [comment]
Hello @anne-duerr ,

the script exists, see https://github.com/VERITAS-Observatory/Eventdisplay_AnalysisScripts_VTS/blob/main/scripts/helper_scripts/UTILITY.readSubmissionCommand.sh

Do you get an error message when running ANALYSIS.anasum.sh? Can you post it here?

**Comment by anne-duerr** [comment]
Hi @GernotMaier,
The script does exist, but ANALYSIS.anasum.sh looks for it in the wrong spot. In line 91, it looks for $(dirname "$0")/VTS/helper_scripts/UTILITY.readSubmissionCommand.sh. The "$EVNDISPSCRIPTS/VTS/helper_scripts" directory does not exist and it results in a "No such file or directory" error:
home/aduerr/bin/Eventdisplay_AnalysisScripts_VTS/scripts/ANALYSIS.anasum.sh: line 91: /home/aduerr/bin/Eventdisplay_AnalysisScripts_VTS/scripts/VTS/helper_scripts/UTILITY.readSubmissionCommand.sh: No such file or directory
Changing line 91 to 
SUBC=`$(dirname "$0")/helper_scripts/UTILITY.readSubmissionCommand.sh`
gets rid of the error.

**Comment by GernotMaier** [comment]
Now I see the issue! 

Fixed and part of the next bug fix release, see pull request #67.
