### ISSUE TITLE
EventDisplay version check error.

### ISSUE THREAD

**Issue by wjin4** [VERITAS-Observatory/Eventdisplay_AnalysisScripts_VTS#74]
In line 8 and 9 of  `"ANALYSIS.anasum_parallel_from_runlist.sh"`, it uses the script `"$EVNDISPSYS/bin/anasum" `to check the version  of EDVERSION and IRFVERSION. This script is not currently exist in the `$EVNDISPSYS/bin` directory. This returns an error when trying to run `"ANALYSIS.anasum_parallel_from_runlist.sh"`. Should I assign the version manually, or there is any script can be used to replace the `"$EVNDISPSYS/bin/anasum"`?

**Comment by GernotMaier** [comment]
You will need `anasum` to run the analysis, without it, it will not work.

Did you compile with `make VERITAS` in $EVNDISPSYS?

**Comment by wjin4** [comment]
My apologies, it's the compiling problem. Somehow I thought it was succeed.
